ALTER TABLE organization
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

ALTER TABLE role
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

ALTER TABLE team
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

ALTER TABLE agent
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

ALTER TABLE goal
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

ALTER TABLE task_item
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
